# # # # # # # #
#   Charul    #
# # # # # # # #

# Uncomment when you finally deploy on production
url: "http://charul.com"
# url: "http://localhost:4000/"

# Basic
trio:
  name:               "Charul's Portfolio"
  description:        "This is a personal site of Charul!"
  
  # Social services usernames
  social:
    github: charulagrl
    twitter: charulagrl
  
  # Google Analytics key, leave blank to ignore
  # google_analytics_key: 
  # Disqus
  disqus_key: charul


# Serving
detach:             false
port:               4000
host:               127.0.0.1
show_dir_listing:   false
baseurl:            ""

permalink:          pretty

# Markdown
markdown:           kramdown
highlighter:        rouge
lsi:                false
excerpt_separator:  "\n\n"
incremental:        false

# Navigation
nav:
  - name:           "About"
    href:           "/"
  - name:           "Projects"
    href:           "/projects/"
  - name:           "Experience"
    href:           "/experience/"

# Sass
sass:
  sass_dir: assets/_sass
  style: :compressed


 
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

gems:
  - jekyll-seo-tag
