# # # # # # # #
#   Charul    #
# # # # # # # #

# Basic
name:               "Charul Personal site"
description:        "This is a personal site of Charul!"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//charul.com"
author:             "Charul"
twitter:
  username:         "charulagrl"
#facebook:
#  app_id:           1234
#    publisher:      1234


# Serving
detach:             false
port:               4000
host:               127.0.0.1
show_dir_listing:   false
baseurl:            ""

permalink:          pretty

# Markdown
markdown:           kramdown
highlighter:        rouge
lsi:                false
excerpt_separator:  "\n\n"
incremental:        false

# Navigation
nav:
  - name:           "About"
    href:           "//kiko.gfjaru.com/about"
  - name:           "Download"
    href:           "//github.com/gfjaru/Kiko/releases"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
